{% set name = "supertree" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe9372219d3a1c5ff432be7c846b9db8043849754a149e2818596eeaf62ba196

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy
    - pandas
    - IPython
    - ipywidgets
    - setuptools

test:
  imports:
    - supertree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mljar/supertree
  summary: Interactive Decision Tree Visualization
  license: AGPL-3.0-only OR LicenseRef-SuperTree-Commerical
  license_file:
    - LICENSE.txt
    - supertree-commercial-license.pdf

extra:
  recipe-maintainers:
    - pplonski
