{% set name = "supertree" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c9966c6e26f9695ca645efa64dd4beb674d863c3efbc2218072ce127c070763

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - pandas
    - IPython
    - ipywidgets

test:
  imports:
    - supertree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mljar/supertree
  summary: Interactive Decision Tree Visualization
  license: AGPL-3.0-only OR LicenseRef-SuperTree-Commerical
  license_file:
    - LICENSE.txt
    - supertree-commercial-license.pdf

extra:
  recipe-maintainers:
    - pplonski
